---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/houses":
    get:
      summary: list houses
      responses:
        '200':
          description: successful
    post:
      summary: create house
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                location:
                  type: string
                price:
                  type: integer
                description:
                  type: string
                image:
                  type: string
              required:
              - name
              - location
              - price
              - description
              - image
  "/api/v1/houses/new":
    get:
      summary: new house
      responses:
        '200':
          description: successful
  "/api/v1/houses/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show house
      responses:
        '200':
          description: successful
    patch:
      summary: update house
      responses:
        '200':
          description: successful
    put:
      summary: update house
      responses:
        '200':
          description: successful
    delete:
      summary: delete house
      responses:
        '200':
          description: successful
  "/api/v1/reservations":
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                start_date:
                  type: string
                end_date:
                  type: string
                status:
                  type: string
                house_id:
                  type: integer
                user_id:
                  type: integer
              required:
              - start_date
              - end_date
              - status
              - house_id
              - user_id
  "/api/v1/reservations/new":
    get:
      summary: new reservation
      responses:
        '200':
          description: successful
  "/api/v1/reservations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show reservation
      responses:
        '200':
          description: successful
    patch:
      summary: update reservation
      responses:
        '200':
          description: successful
    put:
      summary: update reservation
      responses:
        '200':
          description: successful
    delete:
      summary: delete reservation
      responses:
        '200':
          description: successful
  "/api/v1/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3001/
